# fly.toml app configuration file generated for knb-backend on 2026-06-12T12:41:02Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'knb-backend'
primary_region = 'lhr'

[build]
  dockerfile = 'Dockerfile'

[[mounts]]
  source = 'knb_uploads'
  destination = '/app/uploads'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 1

  [[http_service.checks]]
    interval = '30s'
    timeout = '5s'
    grace_period = '20s'
    method = 'GET'
    path = '/api/public/restaurant-info'

[[vm]]
  size = 'shared-cpu-1x'
  memory = '512mb'
